export const colors = [
    {
        color:"Black",
        colorCode:"#000000",
        image:null,
    },
    {
        color:"Silver",
        colorCode:"#C0C0C0",
        image:null,
    },
    {
        color:"red",
        colorCode:"#FF0000",
        image:null,
    },
    {
        color:"blue",
        colorCode:"#0000FF",
        image:null,
    },
    {
        color:"Gold",
        colorCode:"#FFD700",
        image:null,
    },
    {
        color:undefined,
        colorCode:undefined,
        image:null
    }
]