import { Toaster } from 'react-hot-toast';
//import { Toaster } from "@/components/ui/toaster"
import type { Metadata } from 'next'
import { Poppins} from 'next/font/google'
// import { Inter } from 'next/font/google'
import './globals.css'

import {KindeProvider} from "@kinde-oss/kinde-auth-nextjs";
import CartProvider from "../../providers/CartProvider";
//mport Auth from "./auth";
const poppins = Poppins({ subsets: ['latin'] ,weight:["400","700"]})

 /*export const metadata: Metadata = {
  title: 'Create Next App',
 description: 'Generated by create next app',
 }*/

export default  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    // <KindeProvider>
    <html lang="fr">
      
      <body className={poppins.className}>
        <CartProvider>
      <main>{children}</main>
      <Toaster />
      </CartProvider>
      </body>
      
    </html>
    // </KindeProvider>
  )
}
